version: "3.8"
services:
  backend:
    container_name: graphql-server
    mem_limit: 2g
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=thuhuong
      - DB_PASSWORD=thuhuong0208
      - DB_NAME=gatewaydb   

networks:
  mysql-network:
    driver: bridge

