version: "3.8"
services: 
  dev-db: 
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dtth2802
      MYSQL_USER: root
      MYSQL_PASSWORD: dtth2802
      MYSQL_DATABASE: gatewaydb
    networks:
      - mysql-network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile # Points to your Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: mysql://root:dtth2802@dev-db:3306/gatewaydb
      NODE_ENV: .env
    networks:
      - mysql-network
    #command: ["node", "dist/main"] # Starts your NestJS app

networks:
  mysql-network:
    driver: bridge
