version: "3.8"
services:
  dev-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dtth2802
      MYSQL_USER: root
      MYSQL_PASSWORD: dtth2802
      MYSQL_DATABASE: gatewaydb
    networks:
      - mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-server:
    image: controller_webapp_backend-nest-app
    container_name: gateway-server
    env_file:
      - ./production.env
    ports:
      - "8080:8080"
    depends_on:
      dev-db:
        condition: service_healthy
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
